"""Run Axon-emitted kernel source through nkilib's UnitTestFramework.

`AXON_CASE_PATH` points at a self-describing per-case module (generated by
`axon.case_gen`) or a directory of them; each is parametrized into one test.
See the axon-eval skill's `references/harness.md` for the full contract.
"""

import importlib.util
import os
from pathlib import Path

import pytest
from test.utils.common_dataclasses import CompilerArgs, InferenceArgs, Platforms
from test.utils.pytest_test_metadata import pytest_marks, pytest_test_metadata
from test.utils.test_orchestrator import Orchestrator
from test.utils.unit_test_framework import UnitTestFramework, torch_ref_wrapper

_CASE_PATH_ENV = "AXON_CASE_PATH"
_DEFAULT_CASE_PATH = "/tmp/axon_winners"


def _load_module_by_path(source_path, prefix: str):
    p = Path(source_path)
    spec = importlib.util.spec_from_file_location(f"{prefix}_{p.stem}", p)
    if spec is None or spec.loader is None:
        raise ImportError(f"Could not load module from {source_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _discover():
    target = Path(os.environ.get(_CASE_PATH_ENV, _DEFAULT_CASE_PATH))
    if target.is_dir():
        files = sorted(target.glob("*_case.py"))
    elif target.is_file():
        files = [target]
    else:
        files = []
    return [(f, _load_module_by_path(f, "_axon_case")) for f in files]


# Parametrize over the path string only: the runtime param extractor hashes
# every param value and chokes on PosixPath and the loaded module, so re-load
# inside the test body.
_CASES = _discover()
_PARAMS = [pytest.param(str(f), id=m.CASE["name"]) for f, m in _CASES]


@pytest_test_metadata(name="AxonEmitted")
@pytest_marks(["axon_emitted"])
class TestAxonEmitted:
    """Runs Axon-synthesized kernels through nkilib's framework."""

    @pytest.mark.fast
    @pytest.mark.parametrize("case_file", _PARAMS)
    def test_axon_kernel(
        self,
        test_manager: Orchestrator,
        platform_target: Platforms,
        case_file,
    ):
        case_module = _load_module_by_path(case_file, "_axon_case")
        case = case_module.CASE

        kernel_path = Path(case_file).parent / case["kernel_rel"]
        kernel_module = _load_module_by_path(kernel_path, "_axon_emitted")
        kernel_entry = getattr(kernel_module, case["entry_point"])

        shape_args = case["shape_args"]

        def input_generator(test_config):
            return case_module.make_inputs(**shape_args)

        # lnc>=2 winners are SPMD kernels that must compile at logical_nc_config>=2
        # to exercise every core. CASE carries "lnc"; AXON_LNC overrides ad-hoc.
        lnc = int(os.environ.get("AXON_LNC", case.get("lnc", 1)))

        # AXON_NUM_RUNS>1 opts a borderline case into the multi-run protocol
        # (jitter-robust ActiveInferenceTime); absent => single-shot.
        num_runs = int(os.environ.get("AXON_NUM_RUNS", 1))
        inference_args = (
            InferenceArgs(num_runs=num_runs, profile_all_runs=True)
            if num_runs > 1
            else None
        )

        framework = UnitTestFramework(
            test_manager=test_manager,
            kernel_entry=kernel_entry,
            torch_ref=torch_ref_wrapper(case_module.torch_ref),
            kernel_input_generator=input_generator,
            output_tensor_descriptor=case_module.output_tensors,
        )
        framework.run_test(
            test_config=None,
            compiler_args=CompilerArgs(
                platform_target=platform_target, logical_nc_config=lnc
            ),
            atol=case["atol"],
            rtol=case["rtol"],
            inference_args=inference_args,
        )
