"""Axon winner for case 'attention_nkilib_d128', specialized to its tile configuration.

Generated by tools/specialize_winner.py. Do not edit by hand.

This is a standalone kernel: it takes only tensor inputs. The winning tile
configuration is bound as constants in the body, so no caller has to supply
it and the file cannot disagree with the run it came from.

Provenance
----------
    entry point   : attention_nkilib
    shape         : s=1024, d=128
    tile config   : TILES_IN_BLOCK_M=2, TILES_IN_BLOCK_N=8, TILES_IN_BLOCK_K=1, TILES_IN_BLOCK_P=1
    measured      : 41.32 us median (on-device, correct)
    synthesized   : 2026-08-21 23:10:32 UTC (mtime of the source kernel)
    axon commit   : 8617490
    measured on   : trn2.48xlarge, 16 neuron devices, 4 cores each, lnc=2 (host ubuntu@ip-172-31-34-20)

Where the run artifacts live on that host
----------------------------------------
    winner kernel : /home/ubuntu/chunghs-axon/axon/out/winners/attention_nkilib_d128.py
    case metadata : /home/ubuntu/chunghs-axon/axon/out/winners/attention_nkilib_d128_case.py
    run CSV       : /home/ubuntu/chunghs-axon/axon/out/attention_nkilib_d128.csv
    variants+NEFF : /home/ubuntu/chunghs-axon/axon/out/attention_nkilib_d128/
"""

import numpy as np
import nki
import nki.language as nl
import nki.isa as nisa


@nki.jit
def attention_nkilib(q, k_t, v):
    # Specialized to the benched winner's tile configuration.
    TILES_IN_BLOCK_M = 2
    TILES_IN_BLOCK_N = 8
    TILES_IN_BLOCK_K = 1
    TILES_IN_BLOCK_P = 1

    M, K = q.shape
    K_, N = k_t.shape
    N_, P = v.shape
    result = nl.ndarray((M, P), dtype=q.dtype, buffer=nl.shared_hbm)

    TILE_M = 128
    BLOCK_M = TILE_M * TILES_IN_BLOCK_M
    assert M % BLOCK_M == 0, "M must be divisible by BLOCK_M"
    NUM_BLOCK_M = M // BLOCK_M
    assert NUM_BLOCK_M > 0, "M too small for the tile configuration"

    TILE_N = 128
    BLOCK_N = TILE_N * TILES_IN_BLOCK_N
    assert N % BLOCK_N == 0, "N must be divisible by BLOCK_N"
    NUM_BLOCK_N = N // BLOCK_N
    assert NUM_BLOCK_N > 0, "N too small for the tile configuration"

    MATMUL_TILE_N = 512
    TILES_IN_MATMUL_BLOCK_N = BLOCK_N // MATMUL_TILE_N
    while TILES_IN_MATMUL_BLOCK_N == 0:
        MATMUL_TILE_N = MATMUL_TILE_N // 2
        TILES_IN_MATMUL_BLOCK_N = BLOCK_N // MATMUL_TILE_N
    assert TILES_IN_MATMUL_BLOCK_N > 0, "Tile configuration results in zero tiles for matmul"

    TILE_K = 128
    BLOCK_K = TILE_K * TILES_IN_BLOCK_K
    assert K % BLOCK_K == 0, "K must be divisible by BLOCK_K"
    NUM_BLOCK_K = K // BLOCK_K
    assert NUM_BLOCK_K > 0, "K too small for the tile configuration"

    TILE_P = 128
    BLOCK_P = TILE_P * TILES_IN_BLOCK_P
    assert P % BLOCK_P == 0, "P must be divisible by BLOCK_P"
    NUM_BLOCK_P = P // BLOCK_P
    assert NUM_BLOCK_P > 0, "P too small for the tile configuration"

    for m in nl.affine_range(NUM_BLOCK_M):
        nc_transpose_3_sb = nl.ndarray(
            (TILE_N, NUM_BLOCK_N * TILES_IN_BLOCK_N, BLOCK_M),
            dtype=q.dtype, buffer=nl.sbuf)

        nc_matmul_1_sb = (nl.ndarray if NUM_BLOCK_K == 1 else nl.zeros)(
            (TILE_M, TILES_IN_BLOCK_M, N),
            dtype=q.dtype, buffer=nl.sbuf)

        exponential_2_sb = nl.ndarray(
            (TILE_M, TILES_IN_BLOCK_M, N),
            dtype=q.dtype, buffer=nl.sbuf)

        for n in nl.affine_range(NUM_BLOCK_N):
            nc_matmul_1_block = nc_matmul_1_sb[0:TILE_M, 0:TILES_IN_BLOCK_M, (BLOCK_N * n):(BLOCK_N * n) + BLOCK_N]

            for k in nl.sequential_range(NUM_BLOCK_K):
                nc_transpose_0_tiles = nl.ndarray(
                    (TILE_K, TILES_IN_BLOCK_K, BLOCK_M),
                    dtype=q.dtype, buffer=nl.sbuf)
                for b_m in nl.affine_range(TILES_IN_BLOCK_M):
                    for bk_t in nl.affine_range(TILES_IN_BLOCK_K):
                        nc_transpose_0_tiles[0:TILE_K, bk_t, (b_m * TILE_M):(b_m * TILE_M) + TILE_M] = nl.load_transpose2d(
                            q[((TILES_IN_BLOCK_M * m + b_m) * TILE_M):((TILES_IN_BLOCK_M * m + b_m) * TILE_M) + TILE_M,
                                      (BLOCK_K * k + bk_t * TILE_K):(BLOCK_K * k + bk_t * TILE_K) + TILE_K])

                k_t_tiles = nl.ndarray(
                    (TILE_K, TILES_IN_BLOCK_K, BLOCK_N),
                    dtype=k_t.dtype, buffer=nl.sbuf)
                for bk_t in nl.affine_range(TILES_IN_BLOCK_K):
                    nisa.dma_copy(
                        dst=k_t_tiles[0:TILE_K, bk_t, 0:BLOCK_N],
                        src=k_t[((TILES_IN_BLOCK_K * k + bk_t) * TILE_K):((TILES_IN_BLOCK_K * k + bk_t) * TILE_K) + TILE_K,
                             (BLOCK_N * n):(BLOCK_N * n) + BLOCK_N])

                assert BLOCK_N % MATMUL_TILE_N == 0, "BLOCK_N must be divisible by MATMUL_TILE_N"
                for bm in nl.affine_range(TILES_IN_BLOCK_M):
                    for bn in nl.affine_range(TILES_IN_MATMUL_BLOCK_N):
                        ps_nc_matmul_1 = nl.ndarray(
                            (TILE_M, MATMUL_TILE_N), dtype=nl.float32, buffer=nl.psum)
                        nisa.nc_matmul(ps_nc_matmul_1[0:TILE_M, 0:MATMUL_TILE_N],
                            nc_transpose_0_tiles[0:TILE_K, 0, (bm * TILE_M):(bm * TILE_M) + TILE_M],
                            k_t_tiles[0:TILE_K, 0, (bn * MATMUL_TILE_N):(bn * MATMUL_TILE_N) + MATMUL_TILE_N], accumulate=False)
                        for bk_peel in nl.affine_range(TILES_IN_BLOCK_K - 1):
                            bk = bk_peel + 1
                            nisa.nc_matmul(ps_nc_matmul_1[0:TILE_M, 0:MATMUL_TILE_N],
                                nc_transpose_0_tiles[0:TILE_K, bk, (bm * TILE_M):(bm * TILE_M) + TILE_M],
                                k_t_tiles[0:TILE_K, bk, (bn * MATMUL_TILE_N):(bn * MATMUL_TILE_N) + MATMUL_TILE_N], accumulate=True)
                        if NUM_BLOCK_K == 1:
                            nisa.tensor_copy(nc_matmul_1_block[0:TILE_M, bm, (bn * MATMUL_TILE_N):(bn * MATMUL_TILE_N) + MATMUL_TILE_N], ps_nc_matmul_1[0:TILE_M, 0:MATMUL_TILE_N])
                        else:
                            nisa.tensor_tensor(nc_matmul_1_block[0:TILE_M, bm, (bn * MATMUL_TILE_N):(bn * MATMUL_TILE_N) + MATMUL_TILE_N],
                                nc_matmul_1_block[0:TILE_M, bm, (bn * MATMUL_TILE_N):(bn * MATMUL_TILE_N) + MATMUL_TILE_N], ps_nc_matmul_1[0:TILE_M, 0:MATMUL_TILE_N], nl.add)

        tensor_reduce_5_tiles = nl.zeros(
            (TILE_M, TILES_IN_BLOCK_M, 1),
            dtype=nl.float32, buffer=nl.sbuf)
        for n_side in nl.sequential_range(NUM_BLOCK_N):
            for bm_red in nl.affine_range(TILES_IN_BLOCK_M):
                partial_tensor_reduce_5 = nl.ndarray((TILE_M, 1), dtype=nl.float32, buffer=nl.sbuf)
                nisa.activation(exponential_2_sb[0:TILE_M, bm_red, (BLOCK_N * n_side):(BLOCK_N * n_side) + BLOCK_N], nl.exp, nc_matmul_1_sb[0:TILE_M, bm_red, (BLOCK_N * n_side):(BLOCK_N * n_side) + BLOCK_N], reduce_op=nl.add, reduce_res=partial_tensor_reduce_5[0:TILE_M, 0:1], reduce_cmd=nisa.reduce_cmd.reset_reduce)
                nisa.tensor_tensor(tensor_reduce_5_tiles[0:TILE_M, bm_red, 0],
                    tensor_reduce_5_tiles[0:TILE_M, bm_red, 0], partial_tensor_reduce_5[0:TILE_M, 0:1], op=nl.add)

        reciprocal_6_tiles = nl.ndarray(
            (TILE_M, TILES_IN_BLOCK_M, 1),
            dtype=nl.float32, buffer=nl.sbuf)
        for bm_scalar in nl.affine_range(TILES_IN_BLOCK_M):
            nisa.reciprocal(reciprocal_6_tiles[0:TILE_M, bm_scalar, 0], tensor_reduce_5_tiles[0:TILE_M, bm_scalar, 0])

        for n in nl.affine_range(NUM_BLOCK_N):
            exponential_2_stage_tiles = exponential_2_sb[0:TILE_M, 0:TILES_IN_BLOCK_M, (BLOCK_N * n):(BLOCK_N * n) + BLOCK_N]
            nc_transpose_3_inter = nc_transpose_3_sb[0:TILE_N, (TILES_IN_BLOCK_N * n):(TILES_IN_BLOCK_N * n) + TILES_IN_BLOCK_N, 0:BLOCK_M]
            for bn_t in nl.affine_range(TILES_IN_BLOCK_N):
                for bm_t in nl.affine_range(TILES_IN_BLOCK_M):
                    tp_psum_0 = nl.ndarray((TILE_M, TILE_N), dtype=q.dtype, buffer=nl.psum)
                    nisa.nc_transpose(tp_psum_0[0:TILE_M, 0:TILE_N], exponential_2_stage_tiles[0:TILE_M, bm_t, (bn_t * TILE_N):(bn_t * TILE_N) + TILE_N])
                    nisa.tensor_copy(nc_transpose_3_inter[0:TILE_N, bn_t, (bm_t * TILE_M):(bm_t * TILE_M) + TILE_M], tp_psum_0[0:TILE_M, 0:TILE_N])

        for p in nl.affine_range(NUM_BLOCK_P):
            nc_matmul_4_tiles = (nl.ndarray if NUM_BLOCK_N == 1 else nl.zeros)(
                (TILE_M, TILES_IN_BLOCK_M, BLOCK_P),
                dtype=q.dtype, buffer=nl.sbuf)

            for n in nl.sequential_range(NUM_BLOCK_N):
                nc_transpose_3_tiles = nc_transpose_3_sb[0:TILE_N, (TILES_IN_BLOCK_N * n):(TILES_IN_BLOCK_N * n) + TILES_IN_BLOCK_N, 0:BLOCK_M]

                v_tiles = nl.ndarray(
                    (TILE_N, TILES_IN_BLOCK_N, BLOCK_P),
                    dtype=v.dtype, buffer=nl.sbuf)
                for bn_t in nl.affine_range(TILES_IN_BLOCK_N):
                    nisa.dma_copy(
                        dst=v_tiles[0:TILE_N, bn_t, 0:BLOCK_P],
                        src=v[((TILES_IN_BLOCK_N * n + bn_t) * TILE_N):((TILES_IN_BLOCK_N * n + bn_t) * TILE_N) + TILE_N,
                             (BLOCK_P * p):(BLOCK_P * p) + BLOCK_P])

                for bm in nl.affine_range(TILES_IN_BLOCK_M):
                    for bp in nl.affine_range(TILES_IN_BLOCK_P):
                        ps_nc_matmul_4 = nl.ndarray(
                            (TILE_M, TILE_P), dtype=nl.float32, buffer=nl.psum)
                        nisa.nc_matmul(ps_nc_matmul_4[0:TILE_M, 0:TILE_P],
                            nc_transpose_3_tiles[0:TILE_N, 0, (bm * TILE_M):(bm * TILE_M) + TILE_M],
                            v_tiles[0:TILE_N, 0, (bp * TILE_P):(bp * TILE_P) + TILE_P], accumulate=False)
                        for bn_peel in nl.affine_range(TILES_IN_BLOCK_N - 1):
                            bn = bn_peel + 1
                            nisa.nc_matmul(ps_nc_matmul_4[0:TILE_M, 0:TILE_P],
                                nc_transpose_3_tiles[0:TILE_N, bn, (bm * TILE_M):(bm * TILE_M) + TILE_M],
                                v_tiles[0:TILE_N, bn, (bp * TILE_P):(bp * TILE_P) + TILE_P], accumulate=True)
                        if NUM_BLOCK_N == 1:
                            nisa.tensor_copy(nc_matmul_4_tiles[0:TILE_M, bm, (bp * TILE_P):(bp * TILE_P) + TILE_P], ps_nc_matmul_4[0:TILE_M, 0:TILE_P])
                        else:
                            nisa.tensor_tensor(nc_matmul_4_tiles[0:TILE_M, bm, (bp * TILE_P):(bp * TILE_P) + TILE_P],
                                nc_matmul_4_tiles[0:TILE_M, bm, (bp * TILE_P):(bp * TILE_P) + TILE_P], ps_nc_matmul_4[0:TILE_M, 0:TILE_P], nl.add)

            tensor_scalar_7_inter = nl.ndarray((TILE_M, TILES_IN_BLOCK_M, BLOCK_P), dtype=q.dtype, buffer=nl.sbuf)
            for bm_i in nl.affine_range(TILES_IN_BLOCK_M):
                nisa.tensor_scalar(tensor_scalar_7_inter[0:TILE_M, bm_i, 0:BLOCK_P], nc_matmul_4_tiles[0:TILE_M, bm_i, 0:BLOCK_P], nl.multiply, operand0=reciprocal_6_tiles[0:TILE_M, bm_i, 0])

            for bm in nl.affine_range(TILES_IN_BLOCK_M):
                nisa.dma_copy(
                    dst=result[((TILES_IN_BLOCK_M * m + bm) * TILE_M):((TILES_IN_BLOCK_M * m + bm) * TILE_M) + TILE_M,
                           (BLOCK_P * p):(BLOCK_P * p) + BLOCK_P],
                    src=tensor_scalar_7_inter[0:TILE_M, bm, 0:BLOCK_P])

    return result
