"""Axon winner for case 'cumsum_fast_large', specialized to its tile configuration.

Generated by tools/specialize_winner.py. Do not edit by hand.

This is a standalone kernel: it takes only tensor inputs. The winning tile
configuration is bound as constants in the body, so no caller has to supply
it and the file cannot disagree with the run it came from.

Provenance
----------
    entry point   : cumsum
    shape         : m=4096, n=4096
    tile config   : TILES_IN_BLOCK_M=2, TILES_IN_BLOCK_N=2
    measured      : 343.46 us median (on-device, correct)
    synthesized   : 2026-08-25 00:01:12 UTC (mtime of the source kernel)
    axon commit   : 8617490
    measured on   : trn2.48xlarge, 16 neuron devices, 4 cores each, lnc=2 (host ubuntu@ip-172-31-34-20)

Where the run artifacts live on that host
----------------------------------------
    winner kernel : /home/ubuntu/chunghs-axon/axon/out/winners/cumsum_fast_large.py
    case metadata : /home/ubuntu/chunghs-axon/axon/out/winners/cumsum_fast_large_case.py
    run CSV       : /home/ubuntu/chunghs-axon/axon/out/cumsum_fast_large.csv
    variants+NEFF : /home/ubuntu/chunghs-axon/axon/out/cumsum_fast_large/
"""

import numpy as np
import nki
import nki.language as nl
import nki.isa as nisa


@nki.jit
def cumsum(x):
    # Specialized to the benched winner's tile configuration.
    TILES_IN_BLOCK_M = 2
    TILES_IN_BLOCK_N = 2

    TILE_M = 128
    TILE_N = 512
    BLOCK_M = TILES_IN_BLOCK_M * TILE_M
    BLOCK_N = TILES_IN_BLOCK_N * TILE_N

    NUM_BLOCK_M = x.shape[0] // BLOCK_M
    NUM_BLOCK_N = x.shape[1] // BLOCK_N

    assert NUM_BLOCK_M > 0 and NUM_BLOCK_N > 0, \
        "Input size too small for the given tile configuration"

    output = nl.ndarray(
        x.shape, dtype=x.dtype, buffer=nl.shared_hbm)

    for m in nl.affine_range(NUM_BLOCK_M):
        for tile_m in nl.affine_range(TILES_IN_BLOCK_M):
            carry = nl.zeros(
                (TILE_M, 1), dtype=nl.float32, buffer=nl.sbuf)
            for n in nl.sequential_range(NUM_BLOCK_N):
                x_tile = nl.ndarray(
                    (TILE_M, BLOCK_N), dtype=x.dtype, buffer=nl.sbuf)
                nisa.dma_copy(
                    dst=x_tile[0:TILE_M, 0:BLOCK_N],
                    src=x[((TILES_IN_BLOCK_M * m + tile_m) * TILE_M):((TILES_IN_BLOCK_M * m + tile_m) * TILE_M) + TILE_M,
                       (BLOCK_N * n):(BLOCK_N * n) + BLOCK_N])
                out_tile = nl.ndarray(
                    (TILE_M, BLOCK_N), dtype=x.dtype, buffer=nl.sbuf)
                nisa.tensor_scalar_cumulative(
                    dst=out_tile[0:TILE_M, 0:BLOCK_N], src=x_tile[0:TILE_M, 0:BLOCK_N],
                    op0=nl.add, op1=nl.add, imm0=0.0,
                    imm1=carry[0:TILE_M, 0:1],
                    reduce_cmd=nisa.reduce_cmd.load_reduce)
                nisa.dma_copy(
                    dst=output[((TILES_IN_BLOCK_M * m + tile_m) * TILE_M):((TILES_IN_BLOCK_M * m + tile_m) * TILE_M) + TILE_M,
                           (BLOCK_N * n):(BLOCK_N * n) + BLOCK_N],
                    src=out_tile[0:TILE_M, 0:BLOCK_N])
                nisa.tensor_copy(
                    carry[0:TILE_M, 0:1], out_tile[0:TILE_M, (BLOCK_N - 1):(BLOCK_N - 1) + 1])
            REM_N = x.shape[1] % BLOCK_N
            if REM_N:
                x_tail = nl.ndarray(
                    (TILE_M, REM_N), dtype=x.dtype, buffer=nl.sbuf)
                nisa.dma_copy(
                    dst=x_tail[0:TILE_M, 0:REM_N],
                    src=x[((TILES_IN_BLOCK_M * m + tile_m) * TILE_M):((TILES_IN_BLOCK_M * m + tile_m) * TILE_M) + TILE_M,
                       (BLOCK_N * NUM_BLOCK_N):(BLOCK_N * NUM_BLOCK_N) + REM_N])
                out_tail = nl.ndarray(
                    (TILE_M, REM_N), dtype=x.dtype, buffer=nl.sbuf)
                nisa.tensor_scalar_cumulative(
                    dst=out_tail[0:TILE_M, 0:REM_N], src=x_tail[0:TILE_M, 0:REM_N],
                    op0=nl.add, op1=nl.add, imm0=0.0,
                    imm1=carry[0:TILE_M, 0:1],
                    reduce_cmd=nisa.reduce_cmd.load_reduce)
                nisa.dma_copy(
                    dst=output[((TILES_IN_BLOCK_M * m + tile_m) * TILE_M):((TILES_IN_BLOCK_M * m + tile_m) * TILE_M) + TILE_M,
                           (BLOCK_N * NUM_BLOCK_N):(BLOCK_N * NUM_BLOCK_N) + REM_N],
                    src=out_tail[0:TILE_M, 0:REM_N])

    return output
