"""Axon winner for case 'rmsnorm_h8192', specialized to its tile configuration.

Generated by tools/specialize_winner.py. Do not edit by hand.

This is a standalone kernel: it takes only tensor inputs. The winning tile
configuration is bound as constants in the body, so no caller has to supply
it and the file cannot disagree with the run it came from.

Provenance
----------
    entry point   : rmsnorm
    shape         : m=128, n=8192
    tile config   : TILES_IN_BLOCK_M=1, TILES_IN_BLOCK_N=4
    measured      : 35.83 us median (on-device, correct)
    synthesized   : 2026-08-24 23:59:12 UTC (mtime of the source kernel)
    axon commit   : 8617490
    measured on   : trn2.48xlarge, 16 neuron devices, 4 cores each, lnc=2 (host ubuntu@ip-172-31-34-20)

Where the run artifacts live on that host
----------------------------------------
    winner kernel : /home/ubuntu/chunghs-axon/axon/out/winners/rmsnorm_h8192.py
    case metadata : /home/ubuntu/chunghs-axon/axon/out/winners/rmsnorm_h8192_case.py
    run CSV       : /home/ubuntu/chunghs-axon/axon/out/rmsnorm_h8192.csv
    variants+NEFF : /home/ubuntu/chunghs-axon/axon/out/rmsnorm_h8192/
"""

import numpy as np
import nki
import nki.language as nl
import nki.isa as nisa


@nki.jit
def rmsnorm(x):
    # Specialized to the benched winner's tile configuration.
    TILES_IN_BLOCK_M = 1
    TILES_IN_BLOCK_N = 4

    M, N = x.shape
    output = nl.ndarray((M, N), dtype=x.dtype, buffer=nl.shared_hbm)

    TILE_M = 128
    TILE_N = 512
    BLOCK_M = TILE_M * TILES_IN_BLOCK_M
    BLOCK_N = TILE_N * TILES_IN_BLOCK_N
    NUM_BLOCK_M = M // BLOCK_M
    NUM_BLOCK_N = N // BLOCK_N

    assert NUM_BLOCK_M > 0 and NUM_BLOCK_N > 0, \
        "Input size too small for the given tile configuration"

    for m in nl.affine_range(NUM_BLOCK_M):
        accum = nl.zeros(
            (TILE_M, TILES_IN_BLOCK_M, 1),
            dtype=nl.float32, buffer=nl.sbuf)

        for n in nl.sequential_range(NUM_BLOCK_N):
            in_tiles = nl.ndarray(
                (TILE_M, TILES_IN_BLOCK_M, BLOCK_N),
                dtype=x.dtype, buffer=nl.sbuf)
            for tile_m in nl.affine_range(TILES_IN_BLOCK_M):
                nisa.dma_copy(
                    dst=in_tiles[0:TILE_M, tile_m, 0:BLOCK_N],
                    src=x[((TILES_IN_BLOCK_M * m + tile_m) * TILE_M):((TILES_IN_BLOCK_M * m + tile_m) * TILE_M) + TILE_M,
                       (BLOCK_N * n):(BLOCK_N * n) + BLOCK_N])

            for tile_m in nl.affine_range(TILES_IN_BLOCK_M):
                temp_accum = nl.ndarray((TILE_M, 1), dtype=nl.float32, buffer=nl.sbuf)
                activation_reduce_0_act = nl.ndarray(in_tiles[0:TILE_M, tile_m, 0:BLOCK_N].shape, dtype=nl.float32, buffer=nl.sbuf)
                nisa.activation_reduce(activation_reduce_0_act, nl.square, in_tiles[0:TILE_M, tile_m, 0:BLOCK_N], nl.add, reduce_res=temp_accum[0:TILE_M, 0:1])
                nisa.tensor_tensor(accum[0:TILE_M, tile_m, 0],
                    accum[0:TILE_M, tile_m, 0], temp_accum[0:TILE_M, 0:1], op=nl.add)

        for tile_m in nl.affine_range(TILES_IN_BLOCK_M):
            fin_activation_1 = nl.ndarray((TILE_M, 1), dtype=nl.float32, buffer=nl.sbuf)
            nisa.activation(fin_activation_1[0:TILE_M, 0:1], nl.sqrt, accum[0:TILE_M, tile_m, 0])
            fin_reciprocal_2 = nl.ndarray((TILE_M, 1), dtype=nl.float32, buffer=nl.sbuf)
            nisa.reciprocal(fin_reciprocal_2[0:TILE_M, 0:1], fin_activation_1[0:TILE_M, 0:1])
            nisa.tensor_copy(accum[0:TILE_M, tile_m, 0], fin_reciprocal_2[0:TILE_M, 0:1])

        for n in nl.affine_range(NUM_BLOCK_N):
            in_tiles = nl.ndarray(
                (TILE_M, TILES_IN_BLOCK_M, BLOCK_N),
                dtype=x.dtype, buffer=nl.sbuf)
            for tile_m in nl.affine_range(TILES_IN_BLOCK_M):
                nisa.dma_copy(
                    dst=in_tiles[0:TILE_M, tile_m, 0:BLOCK_N],
                    src=x[((TILES_IN_BLOCK_M * m + tile_m) * TILE_M):((TILES_IN_BLOCK_M * m + tile_m) * TILE_M) + TILE_M,
                       (BLOCK_N * n):(BLOCK_N * n) + BLOCK_N])

            for tile_m in nl.affine_range(TILES_IN_BLOCK_M):
                tensor_scalar_3 = nl.ndarray((TILE_M, BLOCK_N), dtype=nl.float32, buffer=nl.sbuf)
                nisa.tensor_scalar(tensor_scalar_3[0:TILE_M, 0:BLOCK_N], in_tiles[0:TILE_M, tile_m, 0:BLOCK_N], nl.multiply, operand0=accum[0:TILE_M, tile_m, 0])
                nisa.dma_copy(
                    dst=output[((TILES_IN_BLOCK_M * m + tile_m) * TILE_M):((TILES_IN_BLOCK_M * m + tile_m) * TILE_M) + TILE_M,
                           (BLOCK_N * n):(BLOCK_N * n) + BLOCK_N],
                    src=tensor_scalar_3[0:TILE_M, 0:BLOCK_N])

    return output
